Project: Smashing Magazine
OlukaDenis/Smashing-Magazine pull request #3
Opened 2019-10-02 17:58 UTC by OlukaDenis

Features:
1. Aligning of elements using grid and flex layouts
2. Application of background shades
3. Using the backgrounds according to the visual hierarchy principles

2019-10-02 18:10 UTC, Redvanisation requested changes
### Hello @OlukaDenis and @Grifo89   🌟

**Good work on this project, but we need to fix the issues below before moving on ⬇️** 

1. The `<footer>` needs to have centered links.

2. Please use the `<main>` semantic HTML tag for the main content of the website.


### _After making the required changes please submit a new code review request_

### Good luck guys! 🍀

2019-10-02 19:28 UTC, Grifo89 commented
Hey @Redvanisation, please just because you can't find errors doesn't mean that you must invent them, We were following some examples sent by students in Odin Project and actually It isn't a 
request to have centered links and less to use main tag here is an example https://bojozahariev.github.io/SmashingDesignTeardown/.

2019-10-02 20:15 UTC, whiz25 commented on index.html
> +    </footer>
Your footer should have **centered links**. Please make them visible by adding some dummy text like ```link-1``` or anything you like. This **[centered links]** is a requirement for the completion of this project.

2019-10-02 20:25 UTC, whiz25 requested changes
## Amazing! :+1: 
This project looks too good. Am impressed.
You have met most of the requirements which is a good thing. However, you have only one thing to make this project complete. Check my comment and implement the requested change.
### [REMINDER]
- The correct use of ```git flow``` is highly emphasized. I know you followed the proper use of git-flow but I believe you can do better. Every feature should have its own branch. For example, the footer, navbar, should all be branches.

#### Make the requested change and re-submit for another review.

2019-10-02 20:50 UTC, Grifo89 commented
We have done with the centered links. Please check it out.

2019-10-02 21:23 UTC, whiz25 requested changes
### You haven't made any changes! :disappointed: 
Make those changes and re-submit.

2019-10-02 21:34 UTC, Grifo89 commented
Sorry, I forgot to push it back!

2019-10-03 03:09 UTC, uche-inyama approved these changes
Good job team! 

I want to apologize on behalf of my colleague, you used the **right flow**, **```github flow```**

Go head and merge and master branch

#### **```Have a Great day```** :slightly_smiling_face:

2019-10-03 12:00 UTC, merged